## Will play Tennis? 

Predicting whether we can play tennis or not from the weather input data

Its straight forward Classification problem and classifying using probabilistic models ( naive bayees )

In [1]:
# Importing libs

import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [2]:
#Importing data
df = pd.read_csv('PlayTennis.csv')
df.head()

Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

# Exploratory Data

In [3]:
#  coverting categorical data in to numerical

number = LabelEncoder()
df['Outlook'] = number.fit_transform(df['Outlook'])
df['Temperature'] = number.fit_transform(df['Temperature'])
df['Humidity'] = number.fit_transform(df['Humidity'])
df['Wind'] = number.fit_transform(df['Wind'])
df['Play Tennis'] = number.fit_transform(df['Play Tennis'])
df.head()


Outlook  Temperature  Humidity  Wind  Play Tennis
0        2            1         0     1            0
1        2            1         0     0            0
2        0            1         0     1            1
3        1            2         0     1            1
4        1            0         1     1            1

In [4]:
unique_Outlook = df['Outlook'].unique()
unique_Outlook

array([2, 0, 1])

In [5]:
y_unique = df['Play Tennis'].unique()
y_unique

array([0, 1])

In [6]:
prior_prob = np.zeros(len(df['Play Tennis'].unique()))
print(prior_prob)
for i in range(0,len(y_unique)):
    prior_prob[i] = sum(df['Play Tennis'] == y_unique[i] / len(df['Play Tennis']))
    print(prior_prob)

[0. 0.]
[5. 0.]
[5. 0.]


In [7]:
features = ['Outlook', 'Temperature', 'Humidity', 'Wind']
target = [ 'Play Tennis']

In [8]:
X = df[features]
Y = df[target]
X.shape , Y.shape

((14, 4), (14, 1))

In [9]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y , test_size= 0.3)
print(X_train.shape , X_test.shape , Y_train.shape , Y_test.shape)

(9, 4) (5, 4) (9, 1) (5, 1)


In [10]:
model = MultinomialNB(alpha=0)
model.fit(X_train,Y_train)

c:\users\user1\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\user1\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\naive_bayes.py:555: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  warnings.warn(


MultinomialNB(alpha=0)

In [11]:
pred = model.predict(X_test)
print(pred)
print(list(Y_test['Play Tennis']))
accuracy = accuracy_score(Y_test,pred)
accuracy

[1 1 1 1 0]
[0, 0, 1, 1, 0]


0.6

In [12]:
# Predicting random input with the model

In [13]:
print(model.predict([[0, 1, 1, 0]]))

[1]


c:\users\user1\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(
